health-check:
    path: /check
    controller: App\Infrastructure\Controller\HealthCheckController

search-beers:
    path: /search
    controller: App\Infrastructure\Controller\SearchBeersController
    methods: [GET]